services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
      # - mysql
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src 
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3307:3306" # Optional: For external access to MySQL
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:17-alpine
    container_name: postgress
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    

  pgadmin4: # http://localhost:5050/login?next=/browser/
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      # PGADMIN_LISTEN_PORT: 8080
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  mysql_data:
  pg_data:
    