version: 0.2

phases:
  pre_build:
    commands:
      - cd next-app
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 919620897356.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=919620897356.dkr.ecr.ap-south-1.amazonaws.com/my-todo-nextjs-app
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-todo-nextjs-app:latest .
      - docker tag my-todo-nextjs-app:latest 919620897356.dkr.ecr.ap-south-1.amazonaws.com/my-todo-nextjs-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 919620897356.dkr.ecr.ap-south-1.amazonaws.com/my-todo-nextjs-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "yt-video-cluster" "919620897356.dkr.ecr.ap-south-1.amazonaws.com/my-todo-nextjs-app:latest" > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
