version: 0.2

phases:
  install:
    commands:
      - DATETIME=$(date +"%Y-%m-%d-%H-%M-%S")

  pre_build:
    commands:
      - cd next-app
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_IID=$(aws sts get-caller-identity --query Account --output text)
      - echo $ACCOUNT_IID
      # - REGIONI=$(aws configure get region)
      # - echo $REGIONI
      - IMAGE_TAGI=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo $IMAGE_TAGI
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 919620897356.dkr.ecr.ap-south-1.amazonaws.com
      - echo $DATETIME
      - echo $ACCOUNT_ID
      - echo $SERVICE_NAME
      - echo $CONTAINER_NAME
      - echo $REPOSITORY_URI
      - echo $TIMESTAMP
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-todo-nextjs-app:latest .
      - docker tag my-todo-nextjs-app:latest 919620897356.dkr.ecr.ap-south-1.amazonaws.com/my-todo-nextjs-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 919620897356.dkr.ecr.ap-south-1.amazonaws.com/my-todo-nextjs-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "RRC-Dev-container" "919620897356.dkr.ecr.ap-south-1.amazonaws.com/my-todo-nextjs-app:latest" > ./../imagedefinitions.json
      - cat ./../imagedefinitions.json

artifacts:
    files: imagedefinitions.json
