version: 0.2

phases:
  install:
    commands:
      - DATETIME=$(date +"%Y-%m-%d-%H-%M-%S")

  pre_build:
    commands:
      - cd next-app
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_IID=$(aws sts get-caller-identity --query Account --output text)
      - echo $ACCOUNT_IID
      # - REGIONI=$(aws configure get region)
      # - echo $REGIONI
      - IMAGE_TAGI=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo $IMAGE_TAGI
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 919620897356.dkr.ecr.ap-south-1.amazonaws.com
      - echo $DATETIME
      - echo $ACCOUNT_ID
      - echo $SERVICE_NAME
      - echo $CONTAINER_NAME
      - echo $TIMESTAMP
      - REPOSITORY_URI=919620897356.dkr.ecr.ap-south-1.amazonaws.com/my-todo-nextjs-app
      - echo $REPOSITORY_URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo $IMAGE_TAG
  build:
    commands:
      - echo Build started on $DATETIME
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on $DATETIME
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "RRC-Dev-container" "919620897356.dkr.ecr.ap-south-1.amazonaws.com/my-todo-nextjs-app:latest" > ./../imagedefinitions.json
      - cp ./../imagedefinitions.json .
      - echo Printing ./../imagedefinitions.json
      - cat ./../imagedefinitions.json
      - echo Printing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
    files: imagedefinitions.json
    secondary-artifacts: {
      imagedefinitions: {
        files: imagedefinitions.json,
        name: imagedefinitions
      }
    }

